name: "🎯 Core Priorities"
description: "Core priorities"
title: "[Core Priority]"
labels: ["Type: OKR"]
body:
  - type: markdown
    id: Objective
    attributes:
      label: "Objective"
  - type: markdown
    id: KR1
    attributes:
      label: "Key Result #1"
  - type: markdown
    id: KR2
    attributes:
      label: "Key Result #2"
  - type: markdown
    id: KR3
    attributes:
      label: "Key Result #3"
  - type: number
    id: Progress
    attributes:
      label: "Progress (% complete)"